"""Room service schemas -- re-export key schemas for convenient imports."""

from app.schemas.room_type import (
    BedConfig,
    RoomTypeCreate,
    RoomTypeListResponse,
    RoomTypeResponse,
    RoomTypeUpdate,
)
from app.schemas.room import (
    RoomCreate,
    RoomDetailResponse,
    RoomListResponse,
    RoomResponse,
    RoomUpdate,
    StatusBoardFloor,
    StatusBoardResponse,
    StatusBoardRoom,
    StatusChangeResponse,
    StatusTransitionRequest,
)
from app.schemas.rate import (
    BaseRateCreate,
    BaseRateResponse,
    BaseRateUpdate,
    NightlyRate,
    PriceCalculationRequest,
    PriceCalculationResponse,
    SeasonalRateCreate,
    SeasonalRateResponse,
    SeasonalRateUpdate,
    WeekendSurchargeCreate,
    WeekendSurchargeResponse,
    WeekendSurchargeUpdate,
)

__all__ = [
    "BedConfig",
    "RoomTypeCreate",
    "RoomTypeUpdate",
    "RoomTypeResponse",
    "RoomTypeListResponse",
    "RoomCreate",
    "RoomUpdate",
    "RoomResponse",
    "RoomDetailResponse",
    "RoomListResponse",
    "StatusTransitionRequest",
    "StatusBoardRoom",
    "StatusBoardFloor",
    "StatusBoardResponse",
    "StatusChangeResponse",
    "BaseRateCreate",
    "BaseRateUpdate",
    "BaseRateResponse",
    "SeasonalRateCreate",
    "SeasonalRateUpdate",
    "SeasonalRateResponse",
    "WeekendSurchargeCreate",
    "WeekendSurchargeUpdate",
    "WeekendSurchargeResponse",
    "PriceCalculationRequest",
    "NightlyRate",
    "PriceCalculationResponse",
]
